name: Second Challenge

on: [push]

env:
    ARTIFACT_ENVIRONMENT_VARIABLE: 'My First Artifact' #Simple declaration

jobs:
    main: #Name of the job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout out this project ##Using Checkout
              uses: actions/checkout@v2

            - name: Artifact Name in both ways ##Just an extra assignment
              run: |
                echo "SHELL: $ARTIFACT_ENVIRONMENT_VARIABLE"
                echo "YAML: ${{ env.ARTIFACT_ENVIRONMENT_VARIABLE }}"

            - name: Upload artifact ##Uploading artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARTIFACT_ENVIRONMENT_VARIABLE }}
                path: . ##Path where I want to save this

