name: Second Challenge
env:
    ARTIFACT_ENVIRONMENT_VARIABLE: 'Artifact Environment Variable'
    OVER_RIDE: 'Artifact'
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Artifact Name
              run: |
                echo "SHELL: $ARTIFACT_ENVIRONMENT_VARIABLE"
                echo "YAML: ${{ env.ARTIFACT_ENVIRONMENT_VARIABLE }}"
            - name: Upload artifact
              uses: actions/upload-artifact@v1.0.0
              with:
                name: Artifact_Name
                path: ./${{ env.ARTIFACT_ENVIRONMENT_VARIABLE }}.txt

